[package]
name = "nbms"
edition = "2021"
repository = "https://github.com/mozilla-services/vpn-network-benchmark"
version = "1.0.0"

[dependencies]
actix-web = "4"
bytes = "1"
dotenv = "0.15.0"
env_logger = "0.9.0"
futures = "0.3"
log = "0.4"
